import { useState } from 'react';
import './Dark.css';
export default function Modes() {
    //useState concept for changing some operations
const [themeChange , setThemeChange] = useState();
    
let ChangeHandler = () =>{
 
    setThemeChange(themeChange ? 'dark' : 'white');
}
    return (
        <>
        <button onClick={ChangeHandler}>Mode</button>
            <p> 
                Lorem ipsum dolor sit amet, consectetur adipisicing elit. Tempora vitae, totam quam non voluptatibus dolorum vel repellat accusantium? Illo at culpa odio, quae dolor tempore voluptatem corporis ducimus atque consectetur. Est temporibus cum beatae laborum. Iusto dolore optio iure nisi voluptas et eaque eius esse, ipsa quisquam voluptates, quod doloremque necessitatibus quaerat laboriosam id, labore at voluptatibus nemo odio non autem facilis omnis sint. Ut omnis, accusantium quisquam voluptas, atque minus totam soluta ullam, ab illo assumenda molestiae ipsum deserunt dolor? Eum quisquam doloremque veniam perferendis? At autem quo odio magni commodi, reiciendis iste aspernatur nemo quia ab est laboriosam itaque consequuntur debitis expedita laborum asperiores voluptas nihil, consequatur beatae, a ducimus unde dignissimos. Eos velit nemo quo sit dolor! Excepturi beatae neque ab, aliquid sed sint atque ea vitae hic dolorem. Accusantium repudiandae nulla harum quam modi velit voluptatibus numquam quis, dignissimos mollitia illo autem amet, ipsa unde ex, facere laborum pariatur! Doloribus veritatis quam unde libero praesentium consectetur mollitia, dolor fugit! Facere ad excepturi iure praesentium odit, fuga rem? Maxime quos quo omnis soluta explicabo quod laborum accusantium illo debitis, libero quaerat, et voluptates. Assumenda aspernatur officiis dignissimos voluptate magnam eaque nobis laudantium corrupti veritatis deserunt delectus et, rem iste eligendi. Facere praesentium, facilis aliquid dolorum dignissimos voluptates iste perspiciatis beatae laborum eligendi cumque consequatur nobis. Quibusdam magnam iste dolor et commodi, expedita neque nam necessitatibus, fuga ex rem soluta! Id commodi modi ut aspernatur ullam adipisci tenetur sint fugit soluta est assumenda, totam ea natus quas sapiente, fuga accusantium, in et animi suscipit beatae! Voluptatibus ipsam consectetur deserunt reprehenderit officia quod eos ex, eaque ipsum nobis qui a vel perspiciatis, repellat nemo quo quibusdam nesciunt dolor voluptate! Fugit quaerat officiis delectus! Tempore a consectetur doloremque sunt minus ullam earum obcaecati vitae aperiam ratione, commodi quasi molestias neque! Quos qui tenetur accusamus ea minima labore iure. Est possimus unde, magni blanditiis corrupti quod laborum perferendis natus, ipsum et fugit asperiores placeat nobis quo sint culpa aliquam obcaecati sit soluta neque, velit debitis quos odio dolorum? Sequi tempora dicta cum necessitatibus accusantium eveniet iste aspernatur aut inventore vel cumque, suscipit reiciendis odit eius doloremque minima libero ut consectetur aliquid! Assumenda perferendis expedita voluptatum facilis illo dolore perspiciatis earum amet nisi adipisci necessitatibus, placeat harum totam explicabo a minus illum possimus nobis distinctio aut unde laudantium, repudiandae eius! Vel tempore unde adipisci consectetur non nihil ipsum quasi reiciendis ipsa mollitia?
                Lorem ipsum dolor sit amet, consectetur adipisicing elit. Tempora vitae, totam quam non voluptatibus dolorum vel repellat accusantium? Illo at culpa odio, quae dolor tempore voluptatem corporis ducimus atque consectetur. Est temporibus cum beatae laborum. Iusto dolore optio iure nisi voluptas et eaque eius esse, ipsa quisquam voluptates, quod doloremque necessitatibus quaerat laboriosam id, labore at voluptatibus nemo odio non autem facilis omnis sint. Ut omnis, accusantium quisquam voluptas, atque minus totam soluta ullam, ab illo assumenda molestiae ipsum deserunt dolor? Eum quisquam doloremque veniam perferendis? At autem quo odio magni commodi, reiciendis iste aspernatur nemo quia ab est laboriosam itaque consequuntur debitis expedita laborum asperiores voluptas nihil, consequatur beatae, a ducimus unde dignissimos. Eos velit nemo quo sit dolor! Excepturi beatae neque ab, aliquid sed sint atque ea vitae hic dolorem. Accusantium repudiandae nulla harum quam modi velit voluptatibus numquam quis, dignissimos mollitia illo autem amet, ipsa unde ex, facere laborum pariatur! Doloribus veritatis quam unde libero praesentium consectetur mollitia, dolor fugit! Facere ad excepturi iure praesentium odit, fuga rem? Maxime quos quo omnis soluta explicabo quod laborum accusantium illo debitis, libero quaerat, et voluptates. Assumenda aspernatur officiis dignissimos voluptate magnam eaque nobis laudantium corrupti veritatis deserunt delectus et, rem iste eligendi. Facere praesentium, facilis aliquid dolorum dignissimos voluptates iste perspiciatis beatae laborum eligendi cumque consequatur nobis. Quibusdam magnam iste dolor et commodi, expedita neque nam necessitatibus, fuga ex rem soluta! Id commodi modi ut aspernatur ullam adipisci tenetur sint fugit soluta est assumenda, totam ea natus quas sapiente, fuga accusantium, in et animi suscipit beatae! Voluptatibus ipsam consectetur deserunt reprehenderit officia quod eos ex, eaque ipsum nobis qui a vel perspiciatis, repellat nemo quo quibusdam nesciunt dolor voluptate! Fugit quaerat officiis delectus! Tempore a consectetur doloremque sunt minus ullam earum obcaecati vitae aperiam ratione, commodi quasi molestias neque! Quos qui tenetur accusamus ea minima labore iure. Est possimus unde, magni blanditiis corrupti quod laborum perferendis natus, ipsum et fugit asperiores placeat nobis quo sint culpa aliquam obcaecati sit soluta neque, velit debitis quos odio dolorum? Sequi tempora dicta cum necessitatibus accusantium eveniet iste aspernatur aut inventore vel cumque, suscipit reiciendis odit eius doloremque minima libero ut consectetur aliquid! Assumenda perferendis expedita voluptatum facilis illo dolore perspiciatis earum amet nisi adipisci necessitatibus, placeat harum totam explicabo a minus illum possimus nobis distinctio aut unde laudantium, repudiandae eius! Vel tempore unde adipisci consectetur non nihil ipsum quasi reiciendis ipsa mollitia?
                Lorem ipsum dolor sit amet, consectetur adipisicing elit. Tempora vitae, totam quam non voluptatibus dolorum vel repellat accusantium? Illo at culpa odio, quae dolor tempore voluptatem corporis ducimus atque consectetur. Est temporibus cum beatae laborum. Iusto dolore optio iure nisi voluptas et eaque eius esse, ipsa quisquam voluptates, quod doloremque necessitatibus quaerat laboriosam id, labore at voluptatibus nemo odio non autem facilis omnis sint. Ut omnis, accusantium quisquam voluptas, atque minus totam soluta ullam, ab illo assumenda molestiae ipsum deserunt dolor? Eum quisquam doloremque veniam perferendis? At autem quo odio magni commodi, reiciendis iste aspernatur nemo quia ab est laboriosam itaque consequuntur debitis expedita laborum asperiores voluptas nihil, consequatur beatae, a ducimus unde dignissimos. Eos velit nemo quo sit dolor! Excepturi beatae neque ab, aliquid sed sint atque ea vitae hic dolorem. Accusantium repudiandae nulla harum quam modi velit voluptatibus numquam quis, dignissimos mollitia illo autem amet, ipsa unde ex, facere laborum pariatur! Doloribus veritatis quam unde libero praesentium consectetur mollitia, dolor fugit! Facere ad excepturi iure praesentium odit, fuga rem? Maxime quos quo omnis soluta explicabo quod laborum accusantium illo debitis, libero quaerat, et voluptates. Assumenda aspernatur officiis dignissimos voluptate magnam eaque nobis laudantium corrupti veritatis deserunt delectus et, rem iste eligendi. Facere praesentium, facilis aliquid dolorum dignissimos voluptates iste perspiciatis beatae laborum eligendi cumque consequatur nobis. Quibusdam magnam iste dolor et commodi, expedita neque nam necessitatibus, fuga ex rem soluta! Id commodi modi ut aspernatur ullam adipisci tenetur sint fugit soluta est assumenda, totam ea natus quas sapiente, fuga accusantium, in et animi suscipit beatae! Voluptatibus ipsam consectetur deserunt reprehenderit officia quod eos ex, eaque ipsum nobis qui a vel perspiciatis, repellat nemo quo quibusdam nesciunt dolor voluptate! Fugit quaerat officiis delectus! Tempore a consectetur doloremque sunt minus ullam earum obcaecati vitae aperiam ratione, commodi quasi molestias neque! Quos qui tenetur accusamus ea minima labore iure. Est possimus unde, magni blanditiis corrupti quod laborum perferendis natus, ipsum et fugit asperiores placeat nobis quo sint culpa aliquam obcaecati sit soluta neque, velit debitis quos odio dolorum? Sequi tempora dicta cum necessitatibus accusantium eveniet iste aspernatur aut inventore vel cumque, suscipit reiciendis odit eius doloremque minima libero ut consectetur aliquid! Assumenda perferendis expedita voluptatum facilis illo dolore perspiciatis earum amet nisi adipisci necessitatibus, placeat harum totam explicabo a minus illum possimus nobis distinctio aut unde laudantium, repudiandae eius! Vel tempore unde adipisci consectetur non nihil ipsum quasi reiciendis ipsa mollitia?

            </p>
        </>
    )
}
